jobs:
  test:
    runs-on: ubuntu-latest
    services:
      mssql:
        image: mysql:5.7
        env:
          MSSQL_SA_PASSWORD: symfonyPASS!123
          ACCEPT_EULA: Y
        ports:
          - 1433
        options: --health-cmd="mssql" --health-interval=10s --health-timeout=5s --health-retries=3
    steps:
    - name: Verify MSSQL connection from host
      run: |
        echo "${{ toJson(job) }}"
        sudo apt-get install -y mssql-tools18
        mssql --host mssql --port ${{ job.services.mysql.ports['3306'] }} -u sa -ppassword -e "symfonyPASS!1234"
        docker logs "${{ job.services.mysql.id }}"
